name: cats-testkit-scalatest
baseurl: /cats-testkit-scalatest
description: Cats Testkit for Scalatest
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 1.0.0-SNAPSHOT
org: org.typelevel
markdown: kramdown
